# Changes here will be overwritten by Copier
_commit: 9f1a16a
_src_path: git@github.com:lhupfeldt/copier_python_package_template.git
author_email: lhn@hupfeldtit.dk
author_name: Lars Hupfeldt Nielsen
company_name: Hupfeldt IT
copyright_holder: Hupfeldt IT
creation_year: 2024
description: Prevent sleep/suspend when (active) SSH or NFS clients.
git_repo_url: https://github.com/lhupfeldt/prevent_sleep.git
github_organization: lhupfeldt
legal_entity: ApS
local_devel_dependency: ''
module_name: prevent_sleep
package_name: prevent-sleep
